[package]
name = "tutor-mgr"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
common_macros = "0.1.1"
iced = { version = "0.14.0", features = ["advanced", "canvas", "svg"] }
lilt = "0.8.1"

[features]
debug = ["iced/hot"]
